backend:
  name: github
  repo: levibrooke/gatsby-netlify-test

publish_mode: editorial_workflow

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields: 
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }